command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: TMDB_SECRET_SCOPE
    value: "tmdb"
  - name: TMDB_SECRET_KEY
    value: "api-key"
  - name: TMDB_API_BASE_URL
    value: "https://api.themoviedb.org/3"
